export const EMAIL_CATEGORIES = {
  APPLICATION_SUBMITTED: "Application Submitted",
  INTERVIEW_REQUEST: "Interview Request",
  REJECTION: "Rejection",
  ASSESSMENT: "Assessment Request",
  OFFER: "Offer",
  FOLLOW_UP: "Follow Up",
  OTHER: "Other",
};

export const CATEGORY_PATTERNS = {
  [EMAIL_CATEGORIES.APPLICATION_SUBMITTED]: [
    "application received",
    "application submitted",
    "thank you for applying",
    "thank you for your application",
    "received your application",
    "successfully submitted",
    "thanks for your interest",
  ],
  [EMAIL_CATEGORIES.INTERVIEW_REQUEST]: [
    "interview",
    "phone screen",
    "next steps",
    "meet with",
    "schedule a call",
    "speak with",
    "schedule a meeting",
    "technical interview",
  ],
  [EMAIL_CATEGORIES.REJECTION]: [
    "unfortunately",
    "not moving forward",
    "other candidates",
    "not selected",
    "decided to pursue",
    "do not match",
    "not a match",
    "no longer under consideration",
  ],
  [EMAIL_CATEGORIES.ASSESSMENT]: [
    "assessment",
    "coding challenge",
    "technical test",
    "assignment",
    "skills test",
    "take-home",
    "online test",
  ],
  [EMAIL_CATEGORIES.OFFER]: [
    "job offer",
    "pleased to offer",
    "offer letter",
    "compensation",
    "formal offer",
    "benefits package",
    "congratulations",
  ],
  [EMAIL_CATEGORIES.FOLLOW_UP]: [
    "check in",
    "following up",
    "reminder",
    "just checking",
    "waiting for your response",
  ],
};
