// src/components/Classification/Categories.js

export const EMAIL_CATEGORIES = {
  APPLICATION_SUBMITTED: "Application Submitted",
  INTERVIEW_REQUEST: "Interview Request",
  REJECTION: "Rejection",
  ASSESSMENT: "Assessment Request",
  OFFER: "Offer",
  FOLLOW_UP: "Follow Up",
  JOB_ALERT: "Job Alert",
  OTHER: "Other",
};

export const CATEGORY_PATTERNS = {
  [EMAIL_CATEGORIES.APPLICATION_SUBMITTED]: [
    "application received",
    "application submitted",
    "thank you for applying",
    "thank you for your application",
    "received your application",
    "successfully submitted",
    "application has been submitted",
    "application confirmation",
    "we have received your application",
    "thank you for submitting",
    "application is complete",
    "has been received",
    "confirming your application",
  ],
  [EMAIL_CATEGORIES.INTERVIEW_REQUEST]: [
    "interview",
    "phone screen",
    "next steps",
    "meet with",
    "schedule a call",
    "speak with",
    "schedule a meeting",
    "technical interview",
    "would like to invite you",
    "interview invitation",
    "conversation with",
    "schedule an interview",
    "video interview",
    "interview process",
    "interview with the team",
    "would like to meet",
  ],
  [EMAIL_CATEGORIES.REJECTION]: [
    "unfortunately",
    "not moving forward",
    "other candidates",
    "not selected",
    "we regret to inform",
    "no longer under consideration",
    "position has been filled",
    "cannot offer you",
    "best of luck",
    "thank you for your understanding",
    "we have decided",
    "not proceeding",
    "regret to inform",
    "we are unable to move forward",
  ],
  [EMAIL_CATEGORIES.ASSESSMENT]: [
    "assessment",
    "coding challenge",
    "technical test",
    "assignment",
    "skills test",
    "take-home",
    "online test",
    "coding assignment",
    "programming challenge",
    "technical assessment",
    "evaluation test",
    "code sample",
    "complete an assessment",
    "please complete the following",
    "assessment link",
  ],
  [EMAIL_CATEGORIES.OFFER]: [
    "job offer",
    "pleased to offer",
    "offer letter",
    "compensation",
    "formal offer",
    "benefits package",
    "congratulations",
    "offer of employment",
    "employment contract",
    "salary offer",
    "offer details",
    "start date",
    "accept this offer",
    "welcome to the team",
    "employment offer",
  ],
  [EMAIL_CATEGORIES.FOLLOW_UP]: [
    "check in",
    "following up",
    "reminder",
    "just checking",
    "waiting for your response",
    "application status",
    "status update",
    "update regarding",
    "any updates",
    "checking the status",
    "touch base",
    "wanted to follow up",
    "update on your application",
    "pending your response",
    "kindly remind",
  ],
  [EMAIL_CATEGORIES.JOB_ALERT]: [
    "job alert",
    "new jobs for you",
    "job recommendations",
    "jobs you might like",
    "matching jobs",
    "new job openings",
    "recommended jobs",
    "top jobs for you",
    "job matches",
    "job opportunities",
    "similar jobs",
    "jobs in your area",
    "career opportunities",
    "job suggestions",
    "new job listings",
  ],
};
